### PR TITLE
Best practice

### PR DESCRIPTION
**Pull request by Vagyasri**
In this project, I have mostly followed the Javascript Best Practices.

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
STATUS: CHANGES REQUIRED 🍀 
Hi There 👋🏾,

I can see you have done a good job but however  a few bugs has appeared in your code which needs to be addressed.

**Comment by alexander16108** [comment]
in the video below it shows a few issues which occur with the page when adding and removing tasks

[click here to view](https://app.usebubbles.com/mTvVni6bxLDEDT4qTjUr9p/comments-on-vagyasri-github-io)

**Comment by Vagyasri** [comment]
Thanks for addressing it, I will fix it ASAP.

**Review by alexander16108 — APPROVED** [review]
STATUS: APPROVED 🥂 

Hi There, Just here to inform you of how much of a good job you did, I have nothing to say but its time to merge........ 🥇

**Pull request merged**
